controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


wx-user-login:
    path: /wx-user/login
    controller: App\Controller\WxUserController::login
wx-user-check-login:
    path: /wx-user/check-login
    controller: App\Controller\WxUserController::checkLogin